### ISSUE TITLE
EscPos.connect got 4 arguments, expected 3

### ISSUE THREAD

**Issue by dorreharay** [leesiongchan/react-native-escpos#2]
I try to connect thermal printer to my react-native app via wifi network.
I call  `await EscPos.connect("192.168.1.118", 9100)` and receive an error `EscPos.connect got 4 arguments, expected 3` .

![error img](https://i.ibb.co/Vgc85ZT/photo-2019-08-03-14-05-53.jpg)

**Comment by leesiongchan** [comment]
Thank you for reporting, I have applied a fix and published a new version, please update and try again.
