### ISSUE TITLE
Compatible ESCPOS list

### ISSUE THREAD

**Issue by KannarFr** [leesiongchan/react-native-escpos#7]
Hi,

Can you provide a list of ESC/POS printers that you tested. I'm new in this domain and I see sile product but no one with good comments...

**Comment by leesiongchan** [comment]
Currently we only use it for one of our client's printer - Xprinter XP-N160II, but I think ESC/POS is kinda like a standard, so as long as your printer supports ESC/POS then it should be working fine.

**Comment by BaiMaoLi** [comment]
It was not working with start-100 printer.
It is supporting ESC/POS.
It does not give any error message, connect status is always true.
